### ISSUE TITLE
Oreganized/Multi-Kulti Title Screen Crash

### ISSUE THREAD

**Issue by Waldough-dev** [TeamGalena/oreganized#109]
### What happened?

After a long and lengthy process of Elimination, I found that the latest update for Oreganized caused some sort of Crash that related to Mixins and "Multi-Kulti". I have attached both the Crash Report below. Please let me know if need anymore information.

### Mod Version

4.2.0

### Minecraft Version

1.20

### Relevant log output

```Shell
https://gist.github.com/Waldough-dev/fe21d9a28613e52c8480410d7786c672
```

**Comment by PssbleTrngle** [comment]
Looks like there is an invalid loot tables somewhere in there in some mod and I should probably catch that instead of crashing

**Comment by PssbleTrngle** [comment]
Should be solved with version `4.2.1`, if not feel free to re-open

**Comment by Waldough-dev** [comment]
Sorry to be the bearer of bad news but there still appears to be some sort of issue occurring. It still appears to be related to Multi-Kulti, Blueprint And Simply Swords. I reverted Oreganized back to the older Version before 4.2.0 and the Game loaded perfectly fine. No Mods were removed. Here is the Link for the Crash Report: https://gist.github.com/Waldough-dev/288a14d14d767e073e7e2c782da5f007
If you'd prefer I open up a new Issue, I will as it appears that I'm unable to reopen this issue.

**Comment by Xasplat** [comment]
The issue persists. Previously the game wouldn't let me join existing words and create new ones, now it won't even start. Here is my log:   https://mclo.gs/0eunZet

**Comment by Xasplat** [comment]
fixed (thanks a lot)
